version: '3.8'
services:
  db:
    container_name: postgres-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  test-db:
    container_name: postgres-test-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=$TEST_DB_USER
      - POSTGRES_PASSWORD=$TEST_DB_PASSWORD
      - POSTGRES_DB=$TEST_DB_NAME
    ports:
      - "6000:5432"
  
  app:
    container_name: backend
    build: ./src
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./docker/static:/app/static
    
volumes:
  postgres_data:
