version: '3.8'
services:
  db:
    container_name: postgres-database
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    container_name: backend
    build: ./src
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./docker/static:/app/static
    
volumes:
  postgres_data:
