"""Initial

Revision ID: 596be087d381
Revises: 
Create Date: 2023-06-09 20:02:27.454913

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '596be087d381'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('salary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('increase_date', sa.Date(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_employee_id'), 'salary', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_id'), 'salary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_id'), table_name='salary')
    op.drop_index(op.f('ix_salary_employee_id'), table_name='salary')
    op.drop_table('salary')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
